import Head from 'next/head';
import Header from '@/Components/Header/Header';
import Footer from '@/Components/Footer/Footer';
import Home from '@/Components/Home/Home';


export default function Index() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <main id='main_content'>
        <Header />
          <Home />
        <Footer />
      </main>
    </>
  )
}
 